### ISSUE TITLE
no issue ...

### ISSUE THREAD

**Issue by crestAT** [Somsubhra/github-release-stats#10]
... just want to say thank you for this really handy and nice tool, very useful !!!

I try to add a pull request for the recently added Total Downloads feature to have it on top of the page, for me this would be more convenient for large projects with many releases ... ;-)

**Comment by crestAT** [comment]
... since  I don't have the permission (of course ... ) I attach my changed files here ...

[Downloads counter on top.zip](https://github.com/Somsubhra/github-release-stats/files/89917/Downloads.counter.on.top.zip)

**Comment by PhrozenByte** [comment]
@crestAT: Simply commit & push your changes to [your fork](https://github.com/crestAT/github-release-stats) (for small changes you can alternatively also [edit the files](https://github.com/crestAT/github-release-stats/edit/master/js/main.js) one by one on GitHub) and [create a new Pull Reqest](https://github.com/crestAT/github-release-stats/pull/new/master). See https://help.github.com/articles/using-pull-requests/ :smiley:
