### ISSUE TITLE
Don't display input user/repo boxes in "result" page

### ISSUE THREAD

**Issue by martinrotter** [Somsubhra/github-release-stats#17]
Let's say I want to embed your superb stats into my project readme.  So I user for example [this](http://www.somsubhra.com/github-release-stats/?username=martinrotter&repository=rssguard) link.

Could you please tweak the look if this "result" page so that it does not include the top "Enter project details..." section and starts directly with the results section?

Maybe just replace the top section with some kind of smaller button "Search another repo...".

Or perhaps just to make sure that page scrolls down to first release in "results" section when link to direct repo results is used?

BTW: Nice project, it was the last piece of stuff I needed to fully switch to GitHub which is better than BitBucket.

**Comment by martinrotter** [comment]
Wow, nice. Checked and working. Thanks man.

**Comment by tooomm** [comment]
While I like the hide-feature from @PhrozenByte in #31 a lot, it has one problem though:
You do not know which repo the stats are for, before you saw that in the search field.
I miss a headline like `User/Repo` or `Organization/Repo` for example.
