### ISSUE TITLE
Loading forever

### ISSUE THREAD

**Issue by borekb** [Somsubhra/github-release-stats#18]
Hi, this is a great little tool and I remember I used it in the past, however, the results don't seem to load on the live version right now, for example:

http://www.somsubhra.com/github-release-stats/?username=versionpress&repository=versionpress

![image](https://cloud.githubusercontent.com/assets/101152/19275862/33d04a50-8fd5-11e6-8918-5944e9cd1e98.png)

**Comment by PhrozenByte** [comment]
Works fine for me. Your IP address has probably exceeded GitHub's rate limit, try again in about an hour. See https://developer.github.com/v3/#rate-limiting

@Somsubhra: It might be a good idea to catch this case and show an error message.

**Comment by borekb** [comment]
Ah OK so I might be on a subnet that already exceeded the limit. I, personally, don't really do any unauthenticated API requests.

**Comment by borekb** [comment]
Oh, it just worked for me perfectly fine. Perhaps some hickup..
