### ISSUE TITLE
Can it show Download count?

### ISSUE THREAD

**Issue by eonist** [Somsubhra/github-release-stats#21]
I tried inserting this: 

https://github.com/eonist/Element/releases/0.0.0-alpha.3/

But no download count.

**Comment by Somsubhra** [comment]
Github only provides download counts of any artifacts that you upload in addition to the source code zip and tar.gz in the release. In your case I don't see any additional uploads, hence no counts.

**Comment by ngotrongphuc** [comment]
Hey, it's 2025 and it seems like there is no download count anymore even though i'm checking a popular package like facebook/react
