### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by kingboyy99** [Somsubhra/github-release-stats#27]
once i enter my username and password, the application just closes and doesn't provide and output or any further information

**Comment by Somsubhra** [comment]
what is the username and repository you are trying to access info for?

**Comment by kingboyy99** [comment]
i'm sorry, but i can't disclose that information.

**Comment by mokun** [comment]
@kingboyy99, it's not asking for the password. Rather, the username and the repository

I put in the following : 

username : jMonkeyEngine
repository : jmonkeyengine

Then I notice that this url is created :  

http://www.somsubhra.com/github-release-stats/?username=jMonkeyEngine&repository=jmonkeyengine

**Comment by tooomm** [comment]
I think this can be closed?

@kingboyy99 Do you understand how this works now?
