### ISSUE TITLE
Github badge support?

### ISSUE THREAD

**Issue by eonist** [Somsubhra/github-release-stats#29]
Feature request 😁

**Comment by martinrotter** [comment]
https://shields.io/

**Comment by eonist** [comment]
A badge that shows downloads dynamically. like `Downloads: 1392`

**Comment by martinrotter** [comment]
It does, it shows Downloads: 11k

**Comment by tooomm** [comment]
He is right, for example:
`https://img.shields.io/github/downloads/eonist/GitSync/total.svg`
will give you: ![](https://img.shields.io/github/downloads/eonist/GitSync/total.svg)

Check the linked page, they have other download badges too.

I guess this can be closed @Somsubhra.

**Comment by eonist** [comment]
@tooomm Wow thats great, if it works. Right now it says `vendor unresponsive`

**Comment by eonist** [comment]
If this works it could be huge for open source apps. As users could easily determine if something is popular or not. Github App Store imminent!

**Comment by tooomm** [comment]
They had some server issues lately. Just give it another try in a few days.
If you see the download badges working on their page, it should work for you too!

**Comment by eonist** [comment]
@tooomm works now. This is huge! I showed it to a few friends and pitched the idea of open source App store. This badge + A "top-list" website with different categories could be huge!
