### ISSUE TITLE
The API call you are using is not correct

### ISSUE THREAD

**Issue by aelassas** [Somsubhra/github-release-stats#47]
According to [GitHub documentation](https://developer.github.com/v3/#pagination), the API call you are using will only returns the first 30 items by default. You are not supporting pagination.

You need to modify your API call by this one for example:

```
https://api.github.com/repos/username/reponame/releases?page=1&per_page=1000000
```

**Comment by ahmetb** [comment]
@Somsubhra hope you can implement pagination or querying more releases. It's returning missing results as indicated. Hope you can let us know if you want to accept a patch. It's a great tool, it would be a shame if we had to rewrite it. :)

**Comment by Somsubhra** [comment]
Patches are welcome :)

**Comment by admkc** [comment]
I opened a pull request #49.

**Comment by Somsubhra** [comment]
This is fixed in the patch by @admkc - closing this. Thanks for the patch!
