### ISSUE TITLE
Connections to the web page fail

### ISSUE THREAD

**Issue by ilg-ul** [Somsubhra/github-release-stats#52]
I'm no longer able to connect to the web site, Firefox complains about security:

```
Secure Connection Failed

An error occurred during a connection to somsubhra.com. PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

Safari has a similar problem.

**Comment by Somsubhra** [comment]
Please continue to use with https://somsubhra.github.io/github-release-stats/

I have given up the earlier custom domain.

**Comment by ilg-ul** [comment]
Yes, but please remove the redirect, as of now GitHub redirects to your custom domain.

**Comment by ilg-ul** [comment]
Sorry, please disregard the previous comment, it was a local cache, I removed it and now I can access the GitHub page.

Thank you!

**Comment by andreynering** [comment]
@Somsubhra Thanks for this project, it's really useful to me!

I came here to check what happened, good to know this is still accessible through another domain. 😉
