### ISSUE TITLE
Support direct links to repo stats

### ISSUE THREAD

**Issue by pochemuto** [Somsubhra/github-release-stats#6]
It would be cool if we could get direct links to repo. 
Add to url usename and repo when "Get the latest release stats" clicked and handle it url params on page loaded. 

Thanks!

**Comment by Somsubhra** [comment]
Yes, there have been many requests for this. So this should be added.

**Comment by Somsubhra** [comment]
The page redirects to http://<APP_ROOT>/?username=<username>&repository=<repository> on clicking on the stats button. Closing this issue.
